on:
  repository_dispatch:
    types: [vercel-deploy]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: e2e-tests
        run: npm ci

      - name: Install Playwright
        working-directory: e2e-tests
        run: npx playwright install --with-deps

      - name: Run tests on live site
        working-directory: e2e-tests
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
        run: |
          echo "Testing site at $BASE_URL"
          npx playwright test --project=chromium --base-url=$BASE_URL
